setup/blackjack/urls.py
from django.urls import path
from .views import home
from . import views
from accounts.views import enter_wager

app_name = 'blackjack'

urlpatterns = [
    path('', home, name='home'),
    path('start_game/', views.start_game, name='start_game'),
    path('enter_wager/', enter_wager, name='enter_wager'),
]

setup/setup/urls.py
from django.contrib import admin
from django.urls import path, include
from blackjack.views import home, start_game


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blackjack/', include('blackjack.urls')),
    path('', home, name='home'),
    path("accounts/", include("accounts.urls")),
    path('start_game/', start_game, name='start_game'),
]

setup/blackjack/models.py
from django.db import models
from django.conf import settings
from .game_engine import GameEngine


# Create your models here.
class game_session(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="games",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

    def play_game(self):
        game = GameEngine()
        game.play_game()

setup/blackjack/views.py
from django.shortcuts import render
from .game_engine import GameEngine
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'blackjack/home.html')


@login_required
def start_game(request):
    user = request.user
    account_balance = request.user.account.balance \
        if request.user.account else 0
    wager = request.POST.get('money')

    if wager and int(wager) <= account_balance:
        wager = int(wager)
        account_balance -= wager
        request.session['initial_wager'] = wager

    initial_wager = request.session.get('initial_wager')

    game_dict = request.session.get('game', None)

    if game_dict is None:
        game = GameEngine()
        game.get_initial_hand()
    else:
        game = GameEngine.from_dict(game_dict)

    context = {
        'player_hand': game.player_hand,
        'dealer_hand': game.dealer_hand,
        'player_sum': game.total(game.player_hand),
        'dealer_sum': game.total(game.dealer_hand),
        'result': None,
        'initial_wager': initial_wager,
        'winnings': initial_wager * 2,
        'new_balance': account_balance + (initial_wager * 2),
        'balance': account_balance,
    }

    if request.method == 'POST':
        action = request.POST.get('action')
        result = None

        if action == 'hit':
            game.deal_card(game.player_hand)
            context['player_sum'] = game.total(game.player_hand)
            player_total = game.total(game.player_hand)
            if player_total > 21:
                result = 'Dealer wins!'
        elif action == 'stay':
            game.player_in = False

            while game.dealer_in:
                dealer_total = game.total(game.dealer_hand)
                if dealer_total >= 17:
                    break
                game.deal_card(game.dealer_hand)
                context['dealer_sum'] = game.total(game.dealer_hand)

            player_total = game.total(game.player_hand)
            dealer_total = game.total(game.dealer_hand)

            if dealer_total > 21:
                result = 'You win!'
                winnings = initial_wager * 2
                account_balance += winnings
                user.account.balance = account_balance
                user.account.save()
            elif dealer_total == 21 and player_total == 21:
                result = "It's a tie!"
                winnings = initial_wager
                account_balance += winnings
                user.account.balance = account_balance
                user.account.save()
            elif player_total > dealer_total:
                result = 'You win!'
                winnings = initial_wager * 2
                account_balance += winnings
                user.account.balance = account_balance
                user.account.save()
            elif player_total < dealer_total:
                result = 'Dealer wins!'
            else:
                result = "It's a tie!"
                winnings = initial_wager
                account_balance += winnings
                user.account.balance = account_balance
                user.account.save()

        if result is not None:
            request.session.pop('game', None)
            request.session.pop('initial_wager', None)
            context['result'] = result
            context['balance'] = account_balance
            return render(request, 'blackjack/start_game.html', context)

    if user.account:
        user.account.balance = account_balance
        user.account.save()

    request.session['game'] = game.to_dict()
    return render(request, 'blackjack/start_game.html', context)

setup/blackjack/templates/blackjack/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Blackjack Game</h1>
    <p>Beat The Dealer. There are some misconceptions about the objective of the game of blackjack but at the simplest level all you are trying to do is beat the dealer.</p>
    <h4>How do you beat the dealer?</h4>
    <ol>
        <li>By drawing a hand value that is higher than the dealer’s hand value</li>
        <li>By the dealer drawing a hand value that goes over 21.</li>
        <li>By drawing a hand value of 21 on your first two cards, when the dealer does not.</li>
    </ol>
    <h4>How do you lose to the dealer? </h4>
    <ol>
        <li>Your hand value exceeds 21.</li>
        <li>The dealers hand has a greater value than yours at the end of the round</li>
    </ol>
    <br>
    <form method="post" action="{% url 'blackjack:start_game' %}">
        {% csrf_token %}
        <label for="money">Enter Wager:</label>
        <div class="input-wrapper">
            <span class="dollar-sign">$</span>
            <input type="number" name="money" id="money" required step="5" min="5" max="{{ user.account.balance }}">
        </div>
        <button type="submit" class="btn">Start Game</button>
        <p class="note">Note: Wager must be in increments of $5</p>
    </form>
    {% if user.account.balance < 5 %}
        <p>You don't have enough balance to play.</p>
    {% endif %}
{% endblock content %}

setup/blackjack/templates/blackjack/master_start_game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description">
    <meta name="keywords">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <title>Blackjack Game</title>
</head>
<body>
    <div class="wrapper">
    <header>
        <nav>
            {% if user.is_authenticated %}
                <h2>Good luck, {{ user.username }}!</h2>
                <ul>
                    {% with user_account=user.account %}
                        {% if user_account %}
                            <li>Balance: ${{ user_account.balance }} {{ user_account.currency }}</li>
                        {% endif %}
                    {% endwith %}
                </ul>
            {% endif %}
        </nav>
    </header>
    <div class="content">
        <h1>Blackjack Game</h1>
        <p>Initial Wager: ${{ initial_wager }}</p>
        <p>Note: Dealer will stand when >= 17</p>
        <h2>
            Dealer's Hand:
            {% if dealer_sum %}{{ dealer_sum }}{% endif %}
        </h2>
        <p>
            {% for card in dealer_hand %}
                {% if forloop.last %}
                    {{ card }}
                {% else %}
                    {{ card }}{% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor %}
        </p>
        <h2>
            Player's Hand:
            {% if player_sum %}{{ player_sum }}{% endif %}
        </h2>
        <p>
            {% for card in player_hand %}
                {% if forloop.last %}
                    {{ card }}
                {% else %}
                    {{ card }}{% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor %}
        </p>
        <br>
        {% if not result %}
        <div class="button-container">
            <form method="post" action="{% url 'start_game' %}">
                {% csrf_token %}
                <input type="hidden" name="action" value="hit">
                <button type="submit" class="btn" aria-label="Hit">Hit</button>
            </form>
            <form method="post" action="{% url 'start_game' %}">
                {% csrf_token %}
                <input type="hidden" name="action" value="stay">
                <button type="submit" class="btn" aria-label="Stay">Stay</button>
            </form>
        </div>
        {% endif %}
        {% if result %}
            <h4>
                {% if result != "It's a tie!" %}{{ result }}{% endif %}
            </h4>
            {% if result != "It's a tie!" %}
                {% if result == "You win!" %}
                    <p>You wagered ${{ initial_wager }}. You won ${{ winnings }}.</p>
                    <p>Your new balance is ${{ new_balance }}.</p>
                {% else %}
                    <p>You wagered ${{ initial_wager }}, so you lost ${{ initial_wager }}.</p>
                    <p>Your new balance is ${{ balance }}.</p>
                {% endif %}
            {% endif %}
            {% if result == "It's a tie!" %}
                <h4>It's a tie!</h4>
                <p>Your wager of ${{ initial_wager }} has been returned to your credits balance.</p>
                <form method="get" action="{% url 'home' %}">
                    <button type="submit" class="btn" aria-label="Play Again">Play Again</button>
                </form>
            {% else %}
                {% if result != "It's a tie!" %}
                    <form method="get" action="{% url 'home' %}">
                        <button type="submit" class="btn" aria-label="Play Again">Play Again</button>
                    </form>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
    <footer class="footer">
        <p>Made by Julius Pagtakhan</p>
    </footer>
    </div>
</body>
</html>

setup/blackjack/templates/blackjack/result.html
{% extends "base.html" %}

{% block content %}
<head>
    <title>Blackjack Game</title>
</head>
<body>
    <h1>Blackjack Game</h1>
    <h2>Game Result</h2>
    <p>Dealer's Hand: {{ revealed_dealer_hand|join:", " }}</p>
    <p>Player's Hand: {{ player_hand|join:", " }}</p>

    {% if session.outcome == "win" %}
        <p>Congratulations! You won the game.</p>
    {% elif session.outcome == "lose" %}
        <p>Sorry! You lost the game.</p>
    {% else %}
        <p>It's a tie!</p>
    {% endif %}

    <a href="{% url 'blackjack:home' %}">Play Again</a>
</body>
{% endblock content %}

setup/blackjack/templates/blackjack/start_game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description">
    <meta name="keywords">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <title>Blackjack Game</title>
</head>
<body>
    <div class="wrapper">
    <header>
        <nav>
            {% if user.is_authenticated %}
                <h2>Good luck, {{ user.username }}!</h2>
                <ul>
                    {% with user_account=user.account %}
                        {% if user_account %}
                            <li>Balance: ${{ user_account.balance }} {{ user_account.currency }}</li>
                        {% endif %}
                    {% endwith %}
                </ul>
            {% endif %}
        </nav>
    </header>
    <div class="content">
        <h1>Blackjack Game</h1>
        <p>Initial Wager: ${{ initial_wager }}</p>
        <p>Note: Dealer will stand when >= 17</p>
        <h2>
            Dealer's Hand:
            {% if dealer_sum %}{{ dealer_sum }}{% endif %}
        </h2>
        <p>
            {% for card in dealer_hand %}
                {% if forloop.last %}
                    {{ card }}
                {% else %}
                    {{ card }}{% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor %}
        </p>
        <h2>
            Player's Hand:
            {% if player_sum %}{{ player_sum }}{% endif %}
        </h2>
        <p>
            {% for card in player_hand %}
                {% if forloop.last %}
                    {{ card }}
                {% else %}
                    {{ card }}{% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor %}
        </p>
        <br>
        {% if not result %}
        <div class="button-container">
            <form method="post" action="{% url 'start_game' %}">
                {% csrf_token %}
                <input type="hidden" name="action" value="hit">
                <button type="submit" class="btn" aria-label="Hit">Hit</button>
            </form>
            <form method="post" action="{% url 'start_game' %}">
                {% csrf_token %}
                <input type="hidden" name="action" value="stay">
                <button type="submit" class="btn" aria-label="Stay">Stay</button>
            </form>
        </div>
        {% endif %}
        {% if result %}
            <h4>
                {% if result != "It's a tie!" %}{{ result }}{% endif %}
            </h4>
            {% if result != "It's a tie!" %}
                {% if result == "You win!" %}
                    <p>You wagered ${{ initial_wager }}. You won ${{ winnings }}.</p>
                    <p>Your new balance is ${{ new_balance }}.</p>
                {% else %}
                    <p>You wagered ${{ initial_wager }}, so you lost ${{ initial_wager }}.</p>
                    <p>Your new balance is ${{ balance }}.</p>
                {% endif %}
            {% endif %}
            {% if result == "It's a tie!" %}
                <h4>It's a tie!</h4>
                <p>Your wager of ${{ initial_wager }} has been returned to your credits balance.</p>
                <form method="get" action="{% url 'home' %}">
                    <button type="submit" class="btn" aria-label="Play Again">Play Again</button>
                </form>
            {% else %}
                {% if result != "It's a tie!" %}
                    <form method="get" action="{% url 'home' %}">
                        <button type="submit" class="btn" aria-label="Play Again">Play Again</button>
                    </form>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
    <footer class="footer">
        <p>Made by Julius Pagtakhan</p>
    </footer>
    </div>
</body>
</html>